server:
  port: 8301

spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: FEBS-Gateway
  cloud:
    gateway:
      routes:
        - id: FEBS-Auth
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/**
        - id: FEBS-Server-System
          uri: lb://FEBS-Server-System
          predicates:
            - Path=/system/**
        - id: FEBS-Server-test
          uri: lb://FEBS-Server-Test
          predicates:
            - Path=/test/**
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS